# Generated by Django 2.1.5 on 2019-01-19 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentBrowsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.Goods')),
            ],
            options={
                'db_table': 'recent_browsing',
            },
        ),
    ]
