# Generated by Django 2.1.5 on 2019-01-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_recentbrowsing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentbrowsing',
            name='click_nums',
            field=models.IntegerField(default=1, verbose_name='点击数'),
        ),
    ]
